# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
es:
  languageCode: es
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/es

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-gb
  contentDir: content/en
  title: CODEC · Research Group
  params:
    description: 'CODEC: Cognitive and Behavioural Sciences research group'
  menu:
    main:
      - name: Tour
        url: en/tour
        weight: 10
      - name: Labs y Research hotbeds
        url: en/post
        weight: 20
      - name: "EvoCo: Human Behaviour and Evolution Lab"
        parent: Labs y Research hotbeds
        url: en/evoco/
        weight: 22
      - name: "LabPsiExp: Experimental Psychology Lab"
        parent: Labs y Research hotbeds
        url: en/labpsiexp/
        weight: 24
      - name: SexCog (sexual cognition research hotbed)
        parent: Labs y Research hotbeds
        url: en/sexcog/
        weight: 26
      - name: NeuroGROUP (neuropsychology research hotbed)
        parent: Labs y Research hotbeds
        url: en/neurogroup/
        weight: 28
      - name: Team
        url: en/people
        weight: 30
      - name: Events
        url: en/event
        weight: 40
      - name: Publications
        url: en/publication
        weight: 50
      - name: Contact
        url: en/contact
        weight: 60
