# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: Laboratorios y Semilleros
    url: group
    weight: 20
  - name: "EvoCo: Laboratorio de Evolución y Comportamiento Humano"
    parent: Laboratorios y Semilleros
    url: evoco/
    weight: 22
  - name: "LabPsiExp: Laboratorio de Psicología Experimental"
    parent: Laboratorios y Semilleros
    url: labpsiexp/
    weight: 24
  - name: SEXCOG (semillero de investigación en cognición sexual)
    parent: Laboratorios y Semilleros
    url: sexcog/
    weight: 26
  - name: NEUROGROUP (semillero de investigación en neuropsicología)
    parent: Laboratorios y Semilleros
    url: neurogroup/
    weight: 28
  - name: Equipo
    url: people
    weight: 30
  - name: Eventos
    url: event
    weight: 40
  - name: Publicaciones
    url: publication
    weight: 50
  - name: Contacto
    url: contact
    weight: 60
